application: wyimgs
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .py
  script: guestbook.app
- url: /images
  static_dir: images

  
libraries:
- name: webapp2
  version: "2.5.2"
